# -*- coding: utf-8 -*-
"""languageprocessor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d-Iym-w-QTW63EeMZCAFbU9eEw_OgWSu

sent.tokenize of the question asked or word lemmatize

lemmatize and tokenize all the sentences in the syllabus and line it up with the question input

line up with pre coded FAQS

extract all definitions from the book

if keyword define is used only search in the definition db


otherwise compare input nad use cosine similarity to determine which precorded answer to use 
"""
import io
import random
import string 
import warnings
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import nltk
nltk.download()

from nltk.stem import WordNetLemmatizer

lemma= nltk.stem.WordNetLemmatizer()
#simplify the sentence 
def cleaning(sentence):
    sentencewords = nltk.word_tokenize(sentence)
    sentencewords = [lemma.lemmatize(word.lower()) for word in sentencewords]
    return sentencewords



